version: "3.9"

services:
  web:
    build: .
    container_name: dsw_webhook
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - web
    command: http web:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"  # ngrok web interface


